# Generated by Django 5.0.6 on 2024-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='notesfile',
        ),
        migrations.AddField(
            model_name='notes',
            name='file_type',
            field=models.CharField(default='PDF', max_length=50),
        ),
        migrations.AddField(
            model_name='notes',
            name='notes_file',
            field=models.FileField(default=2, upload_to='notes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
